import jaydebeapi
# pip install JayDeBeApi

def ejemplo1():
    driver = 'org.hsqldb.jdbcDriver'
    #hsqldb_jar = './PYTHON/PYTHON_0026/Ejemplo1/hsqldb.jar'
    hsqldb_jar = 'C:\\CERTIFICADO\\PYTHON\Ejemplo25\\hsqldb.jar'
    usuario = 'SA'
    contrasena = '12345678'
    url = 'jdbc:hsqldb:file:/PYTHON/Ejemplo25/datos'
    conexion = None
    try:
        conexion = jaydebeapi.connect(
        driver,
        url,
        [usuario, contrasena],
        hsqldb_jar)
    except:
        conexion = None

    if conexion != None:
       print('OK: CONEXION')
    else:
       print('ERROR: CONEXION')

def BaseDatosHsqldb():
    driver = 'org.hsqldb.jdbcDriver'
    #hsqldb_jar = './PYTHON/PYTHON_0026/Ejemplo1/hsqldb.jar'
    hsqldb_jar = 'C:\\CERTIFICADO\\PYTHON\\Ejemplo25\\hsqldb.jar'
    usuario = 'SA'
    contrasena = '12345678'
    url = 'jdbc:hsqldb:file:/PYTHON/Ejemplo25/datos'
    conexion = None
    try:
        conexion = jaydebeapi.connect(
        driver,
        url,
        [usuario, contrasena],
        hsqldb_jar)
    except:
        conexion = None
    return conexion


def ejemplo2():
    conexion = BaseDatosHsqldb()

    if conexion != None:
       print('OK: CONEXION')
       try:
            # Si ponemos not null en id_comprador da error
            query = '''CREATE TABLE Comprador ( 
                          id_comprador      INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                          nombre            VARCHAR(25) NOT NULL,
                          apellidos         VARCHAR(50) NOT NULL,
                          fecha_nacimiento  DATE        NOT NULL
                       )'''                 # Query create table
            cursor = conexion.cursor()      # Crear cursor
            cursor.execute(query)           # Ejecutar query. No producen resultado en el cursor

            print('OK: CREATE TABLE')
       except:   
            print('ERROR: CREATE TABLE')
       finally:
            cursor.close()
            conexion.close()

    else:
       print('ERROR: CONEXION')

ejemplo2()